// Host test for the experimental global-table Huffman decoder (pnx_huffman.c) --
// correctness of pnx_huffman_table_parse + pnx_huffman_decode against a real shared
// table generated by tools/gen_huffman_fixtures.py from the SAME real pixel content
// bpeg_fixtures.h carries (tools/bpeg2_prototype.py's already-validated
// encode_asset_shared_table), so this checks the C port against known-good encoder
// output, not hand-crafted bytes.
//
// Standalone: pnx_huffman.c is not yet wired into pnx_sprite_load/atlas_load_into, so
// this is the only place it runs.

#include "../src/pnx/pnx_config.h"

#if PNX_COMPRESS_MODE == PNX_COMPRESS_HUFFMAN

#include "../src/pnx/assets/pnx_huffman.h"
#include "fixtures/huffman/pnx_huffman_fixtures.h"
#include "fixtures/huffman/pnx_huffman_pipeline_fixtures.h"

#include <stdio.h>
#include <string.h>

extern int s_failures;
extern int s_checks;

#define HC_CHECK(cond)                                               \
	do                                                               \
	{                                                                \
		s_checks++;                                                  \
		if (!(cond))                                                 \
		{                                                            \
			printf("  FAIL %s:%d  %s\n", __FILE__, __LINE__, #cond); \
			s_failures++;                                            \
		}                                                            \
	} while (0)

void test_huffman_compress(void);

void test_huffman_compress(void)
{
	printf("huffman_compress\n");

	static uint16_t symbols[PNX_HUFFMAN_TABLE_MAX_COLS];
	PnxHuffmanTable table;
	const bool parsed = pnx_huffman_table_parse(&table, pnx_huffman_test_table,
												sizeof(pnx_huffman_test_table), symbols,
												PNX_HUFFMAN_TABLE_MAX_COLS);
	HC_CHECK(parsed);
	if (!parsed)
		return;

	static uint8_t dst[4096];
	static uint8_t scratch[8192];

	for (int i = 0; i < PNX_HUFFMAN_FIXTURE_COUNT; i++)
	{
		const PnxHuffmanFixture* f = &pnx_huffman_fixtures[i];
		memset(dst, 0xAA, sizeof(dst));
		const bool ok = pnx_huffman_decode(&table, f->encoded, f->encoded_len, dst, scratch, f->n);
		HC_CHECK(ok);
		if (!ok)
		{
			printf("  decode failed: %s\n", f->name);
			continue;
		}

		uint8_t packed_expected[2048];
		for (uint16_t j = 0; j < f->n; j += 2)
		{
			const uint8_t hi	   = f->expected[j];
			const uint8_t lo	   = (uint16_t)(j + 1) < f->n ? f->expected[j + 1] : 0;
			packed_expected[j / 2] = (uint8_t)((hi << 4) | lo);
		}
		const size_t packed_len = ((size_t)f->n + 1) / 2;
		const bool match		= memcmp(dst, packed_expected, packed_len) == 0;
		HC_CHECK(match);
		if (!match)
			printf("  MISMATCH: %s\n", f->name);
	}

	// --- malformed input must refuse cleanly, not crash or overrun ---
	HC_CHECK(!pnx_huffman_decode(&table, NULL, 0, dst, scratch, 16));
	{
		uint8_t garbage[2] = { 0x01, 0x00 }; // k=2, coded, but no bitstream follows at all
		HC_CHECK(!pnx_huffman_decode(&table, garbage, sizeof(garbage), dst, scratch, 256));
	}

	// --- a table that claims more columns than the caller's buffer holds is refused ---
	{
		static uint16_t tiny_symbols[1];
		PnxHuffmanTable bad;
		HC_CHECK(!pnx_huffman_table_parse(&bad, pnx_huffman_test_table, sizeof(pnx_huffman_test_table),
										  tiny_symbols, 1));
	}

	// --- the REAL pipeline's own output (tools/pnx_assets.py, compress = "huffman", run
	// against Need4Pebble's actual content), not synthetic data -- see
	// tools/gen_huffman_pipeline_fixtures.py.
	static uint16_t pipeline_symbols[PNX_HUFFMAN_TABLE_MAX_COLS];
	PnxHuffmanTable pipeline_table;
	const bool pipeline_parsed = pnx_huffman_table_parse(
		&pipeline_table, pnx_huffman_pipeline_table, sizeof(pnx_huffman_pipeline_table),
		pipeline_symbols, PNX_HUFFMAN_TABLE_MAX_COLS);
	HC_CHECK(pipeline_parsed);
	if (!pipeline_parsed)
		return;

	for (int i = 0; i < PNX_HUFFMAN_PIPELINE_FIXTURE_COUNT; i++)
	{
		const PnxHuffmanFixture* f = &pnx_huffman_pipeline_fixtures[i];
		memset(dst, 0xAA, sizeof(dst));
		const bool ok = pnx_huffman_decode(&pipeline_table, f->encoded, f->encoded_len, dst,
										   scratch, f->n);
		HC_CHECK(ok);
		if (!ok)
		{
			printf("  pipeline decode failed: %s\n", f->name);
			continue;
		}
		uint8_t packed_expected[2048];
		for (uint16_t j = 0; j < f->n; j += 2)
		{
			const uint8_t hi	   = f->expected[j];
			const uint8_t lo	   = (uint16_t)(j + 1) < f->n ? f->expected[j + 1] : 0;
			packed_expected[j / 2] = (uint8_t)((hi << 4) | lo);
		}
		const size_t packed_len = ((size_t)f->n + 1) / 2;
		const bool match		= memcmp(dst, packed_expected, packed_len) == 0;
		HC_CHECK(match);
		if (!match)
			printf("  PIPELINE MISMATCH: %s\n", f->name);
	}
}

#endif // PNX_COMPRESS_MODE == PNX_COMPRESS_HUFFMAN
