// Host test for the experimental bitplane/Elias-gamma decoder (pnx_bitplane.c) --
// correctness against real, encoded-offline prepackaged sprite frames and atlas tiles
// (fixtures/bitplane/bpeg_fixtures.h, generated by tools' bpeg_encode.py mirror in the
// investigating session, not part of the pipeline), plus a first real decode-cost
// number against a plain 4bpp unpack and against pnx_lzss_decode on equivalent bytes --
// the one thing the whole compression investigation never had until now.
//
// Standalone: pnx_bitplane.c is not wired into pnx_sprite_load/atlas_load_into, so this
// is the only place it runs.

#include "../src/pnx/pnx_config.h"

#if PNX_USE_BITPLANE_COMPRESS

#include "../src/pnx/assets/pnx_bitplane.h"
#include "fixtures/bitplane/bpeg_fixtures.h"

#include <stdio.h>
#include <string.h>
#include <time.h>

#if PNX_USE_MAP_COMPRESS || PNX_USE_SPRITE_COMPRESS || PNX_USE_ATLAS_COMPRESS
#include "../src/pnx/assets/pnx_lzss.h"
#define HAVE_LZSS 1
#else
#define HAVE_LZSS 0
#endif

extern int s_failures;
extern int s_checks;

#define BC_CHECK(cond)                                               \
	do                                                               \
	{                                                                \
		s_checks++;                                                  \
		if (!(cond))                                                 \
		{                                                            \
			printf("  FAIL %s:%d  %s\n", __FILE__, __LINE__, #cond); \
			s_failures++;                                            \
		}                                                            \
	} while (0)

void test_bitplane_compress(void);

void test_bitplane_compress(void)
{
	printf("bitplane_compress\n");

	static uint8_t dst[4096];
	static uint8_t scratch[8192];

	// --- correctness, every fixture ---
	for (int i = 0; i < BPEG_FIXTURE_COUNT; i++)
	{
		const BpegFixture* f = &BPEG_FIXTURES[i];
		memset(dst, 0xAA, sizeof(dst));
		const bool ok = pnx_bitplane_decode(f->encoded, f->encoded_len, dst, scratch, f->n);
		BC_CHECK(ok);
		if (ok)
		{
			// `expected` is unpacked (one real palette index per byte), same shape
			// bpeg_encode.py's decode_unit returns -- pack it here rather than
			// regenerate every fixture, since pnx_bitplane_decode's own output is now
			// packed 4bpp.
			uint8_t packed_expected[2048];
			for (uint16_t j = 0; j < f->n; j += 2)
			{
				const uint8_t hi	   = f->expected[j];
				const uint8_t lo	   = (uint16_t)(j + 1) < f->n ? f->expected[j + 1] : 0;
				packed_expected[j / 2] = (uint8_t)((hi << 4) | lo);
			}
			const size_t packed_len = ((size_t)f->n + 1) / 2;
			const bool match		= memcmp(dst, packed_expected, packed_len) == 0;
			BC_CHECK(match);
			if (!match)
				printf("  MISMATCH: %s\n", f->name);
		}
	}

	// --- malformed input must refuse cleanly, not crash or overrun ---
	{
		uint8_t garbage[3] = { 0x05, 0xFF, 0xFF }; // header claims k=6 (bits=3), no room
		BC_CHECK(!pnx_bitplane_decode(garbage, sizeof(garbage), dst, scratch, 256));
	}
	BC_CHECK(!pnx_bitplane_decode(NULL, 0, dst, scratch, 16));

	// --- decode cost: bitplane+EG vs a plain 4bpp unpack vs LZSS, same real content ---
	// Host wall-clock only -- ordering information, not a device number (same caveat
	// docs/MEASUREMENTS.md's own host timing sections always carry).
	{
		const int iters		= 20000;
		double total_pixels = 0;

		clock_t t0 = clock();
		for (int rep = 0; rep < iters; rep++)
		{
			for (int i = 0; i < BPEG_FIXTURE_COUNT; i++)
			{
				const BpegFixture* f = &BPEG_FIXTURES[i];
				pnx_bitplane_decode(f->encoded, f->encoded_len, dst, scratch, f->n);
				if (rep == 0)
					total_pixels += f->n;
			}
		}
		clock_t t1				  = clock();
		const double bp_secs	  = (double)(t1 - t0) / CLOCKS_PER_SEC;
		const double bp_ns_per_px = (bp_secs * 1e9) / (iters * total_pixels);

		// Floor comparison: both source and destination are packed 4bpp now (decode no
		// longer produces one-byte-per-pixel output), so the honest zero-transformation
		// baseline is a straight copy, not an unpack -- this is the cost bitplane+EG's
		// decode work is paying ON TOP OF, not the cost of packing itself.
		static uint8_t packed_src[4096];
		size_t packed_total = 0;
		for (int i = 0; i < BPEG_FIXTURE_COUNT; i++)
		{
			const BpegFixture* f	= &BPEG_FIXTURES[i];
			const size_t packed_len = ((size_t)f->n + 1) / 2;
			for (uint16_t j = 0; j < f->n; j += 2)
			{
				const uint8_t hi				 = f->expected[j];
				const uint8_t lo				 = (uint16_t)(j + 1) < f->n ? f->expected[j + 1] : 0;
				packed_src[packed_total + j / 2] = (uint8_t)((hi << 4) | lo);
			}
			packed_total += packed_len;
		}
		clock_t t2 = clock();
		for (int rep = 0; rep < iters; rep++)
			memcpy(dst, packed_src, packed_total);
		clock_t t3				   = clock();
		const double raw_secs	   = (double)(t3 - t2) / CLOCKS_PER_SEC;
		const double raw_ns_per_px = (raw_secs * 1e9) / (iters * total_pixels);

		printf("  bitplane+EG decode : %.2f ns/pixel\n", bp_ns_per_px);
		// memcpy of ~2KB is near the noise floor of clock()'s resolution on host --
		// prints, but not a ratio worth computing against; the real, worth-trusting
		// floor comparison is the device bench (examples/bitplanebench).
		printf("  packed memcpy floor: %.4f ns/pixel (too fast to ratio meaningfully here)\n",
			   raw_ns_per_px);

#if HAVE_LZSS
		// LZSS side: the SAME fixture pixels, pre-compressed offline as one concatenated
		// stream (the realistic shape LZSS actually runs in -- one blob, not per-unit),
		// timed decoding all of it back in one call. Deliberately not apples-to-apples on
		// STRUCTURE -- LZSS never decodes a fraction of a blob the way bitplane+EG
		// decodes just one tile, that random-access property is the whole reason this
		// format exists -- this is only a same-content relative CPU-cost check.
		static uint8_t lzss_dst[BPEG_ALL_PACKED_LEN];
		clock_t t4 = clock();
		for (int rep = 0; rep < iters; rep++)
			pnx_lzss_decode(BPEG_ALL_PACKED_LZSS, sizeof(BPEG_ALL_PACKED_LZSS), lzss_dst,
							sizeof(lzss_dst));
		clock_t t5					= clock();
		const double lzss_secs		= (double)(t5 - t4) / CLOCKS_PER_SEC;
		const double lzss_ns_per_px = (lzss_secs * 1e9) / (iters * total_pixels);
		BC_CHECK(memcmp(lzss_dst, BPEG_ALL_PACKED_RAW, sizeof(lzss_dst)) == 0);
		printf("  LZSS decode        : %.2f ns/pixel (whole-blob, not per-tile)\n",
			   lzss_ns_per_px);
#endif

		BC_CHECK(bp_ns_per_px > 0.0);
	}
}

#else

void test_bitplane_compress(void);
void test_bitplane_compress(void)
{
}

#endif // PNX_USE_BITPLANE_COMPRESS
