// GENERATED by tools/pnx_assets.py -- do not edit.
//
// Regenerate with the manifest, never by hand. Nothing here should be typed
// into game code by name: use the symbols, not the numbers.

#pragma once

#include <stdint.h>
#include <stddef.h> // NULL -- a sprite clip with no authored per-frame
					// durations emits its _DURATIONS symbol as this, not an
					// array (see the sprite loop below)

// Built for orientation buttons_right. Every dimension and coordinate
// below is in the FRAMEBUFFER's frame, already rotated -- a map that reads 32
// wide in the manifest reports 24 here if that is what the display sees. Pass
// this to pnx_assets_expect_orientation() at start-up and a blob left over from
// a build in the other orientation is a clean refusal rather than scrambled art.
#define PNX_ORIENTATION 0

// Stable asset handles. Index into the runtime registry.
typedef enum
{
	PNX_ASSET_PALETTES_PALETTES,
	PNX_ASSET_ATLAS_TILES,
	PNX_ASSET_COUNT
} PnxAssetId;

// The runtime loads palettes by this fixed slot before anything indexes them.
_Static_assert(PNX_ASSET_PALETTES_PALETTES == 0,
			   "palettes must be asset 0");

#ifndef PNX_PLATFORM_HOST
// RESOURCE_ID_* constants, generated by the SDK from package.json. This is
// pure integer #defines with no Pebble API in it, so including it here does
// not breach the rule that only the platform layer may touch the SDK -- and
// it is the only way game code can name a resource without <pebble.h>.
#include "src/resource_ids.auto.h"

// Maps each handle to its Pebble resource, in the same order as the enum.
#define PNX_ASSET_RESOURCE_TABLE { \
	RESOURCE_ID_PALETTES,          \
	RESOURCE_ID_TILES,             \
}
#else
// The host has no resource ids, only files. Emitted for the same reason the
// table above is: a hand-written list of blob paths in a test goes stale the
// moment the manifest gains an asset, and the symptom is a scene failing for
// a reason that has nothing to do with scenes.
#define PNX_ASSET_FILE_TABLE { \
	"palettes.bin",            \
	"tiles.bin",               \
}
#endif

#define TILES_TILE_PX		16
#define TILES_TILE_BYTES	128
#define TILES_TILE_COUNT	4
#define TILES_PALETTE_COUNT 1

// Shared palette table. PNX_PALETTE_SLOTS must be at least this.
#define PNX_PALETTES_USED 1

// Tile roles from the manifest legend, resolved per atlas. Prefixed by
// atlas name because two tilesets may both define a role called 'wall'.
#define TILES_TILE_ACCENT 0
#define TILES_TILE_FLOOR  1
#define TILES_TILE_WALL	  3
#define TILE_ACCENT		  0
#define TILE_FLOOR		  1
#define TILE_WALL		  3
