#!/usr/bin/env python3
"""Writes assets.toml for the lzssbench example.

M12 (see docs/ROADMAP.md) built cell-dictionary + LZSS map compression and measured its
resource-size and runtime-code-size cost for real, but left one thing open: how long
`pnx_lzss_decode` actually takes on a Cortex-M when a bank streams in. This app answers
that, on a device, rather than guessing.

Four maps of the same shape -- a walled room, floor, and a sprinkle of a third tile, the
3-distinct-value case every real map in the repo lands close to -- at four sizes: 16x16
up to 192x192 (the same footprint as `worldtiles/plain`'s field, the largest map anywhere
in the repo, so the top of this sweep is not a hypothetical). Held resident (`resident =
true`) rather than streamed: this app calls `pnx_lzss_decode` directly against every bank
a map owns, not through `pnx_map_stream`'s window, so how the pool would evict is not in
scope and residency keeps the WorldTile grid simple to reason about.

Re-run to change the sizes:

    python3 examples/lzssbench/generate.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Same three roles every real map's dictionary settles on: floor, wall, a sparse accent.
# `pick_worldtile` in the pipeline sizes the WorldTile grid itself; nothing here forces a
# particular bank count, so the sweep is real pipeline output at each size, not a rigged
# single-bank case.
SIZES = [16, 32, 96, 192]


def room(size):
    """A walled square: border '#', floor '.', 'A' every 11th cell on an interior
    diagonal-ish stride -- sparse and irregular enough that LZSS earns its keep on
    matches rather than compressing a literal solid fill."""
    rows = []
    for y in range(size):
        if y == 0 or y == size - 1:
            rows.append("#" * size)
            continue
        row = []
        for x in range(size):
            if x == 0 or x == size - 1:
                row.append("#")
            elif (x * 3 + y * 7) % 29 == 0:
                row.append("A")
            else:
                row.append(".")
        rows.append("".join(row))
    return "\n".join(rows)


HEADER = '''# GENERATED by generate.py -- do not edit by hand, see that file's own header.
#
# Four maps, one shape, four sizes -- a decode-cost sweep against real, pipeline-built
# LZSS banks. See generate.py for why these particular sizes and why `resident = true`.

[project]
name = "lzssbench"
resources = "resources"
header = "src/c/assets_gen.h"
compress_maps = true
budget_bytes = 262144

[[font]]
name = "bench"
source = "art/fonts/LiberationSans-Regular.ttf"
size = 14
depth = 1
threshold = 128
charset = " !%()+-./0123456789:ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
license = "SIL Open Font License 1.1"
out = "font_bench.bin"

[[atlas]]
name = "tiles"
sheet = "art/tileset.png"
tile = 16
region = [0, 0, 6, 1]
max_tiles = 6
out = "tiles.bin"
autopick = ["floor", "wall", "accent"]

[[atlas.collision]]
tile = "wall"
type = "solid"

[legend."."]
tile = "floor"
flags = []
[legend."#"]
tile = "wall"
flags = []
[legend."A"]
tile = "accent"
flags = []

'''


def main():
    out = [HEADER]
    for size in SIZES:
        out.append(f'[[map]]\n')
        out.append(f'name = "s{size}"\n')
        out.append(f'out = "map_s{size}.bin"\n')
        out.append(f'start = [1, 1]\n')
        out.append(f'resident = true\n')
        out.append(f'warps = []\n')
        out.append('rows = """\n')
        out.append(room(size))
        out.append('\n"""\n\n')

    path = os.path.join(HERE, "assets.toml")
    with open(path, "w") as f:
        f.write("".join(out))
    print(f"wrote {path}  ({len(SIZES)} maps: {SIZES})")


if __name__ == "__main__":
    main()
