#!/usr/bin/env python3
"""Generates tests/fixtures/huffman/pnx_huffman_pipeline_fixtures.h directly from a REAL
pipeline build's output (tools/pnx_assets.py, compress = "huffman") -- closes the loop
between the C decoder (pnx_huffman.c) and the actual bytes the real pipeline emits,
not just the synthetic-from-bpeg_fixtures.h data gen_huffman_fixtures.py produces.

Usage: python3 tools/gen_huffman_pipeline_fixtures.py <huffman_resources_dir> <none_resources_dir>
(the same two directories tools/verify_huffman_pipeline.py compares, at whatever scratch
path they were built to.)
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import bpeg2_prototype as bp2

HUF_DIR = Path(sys.argv[1])
NONE_DIR = Path(sys.argv[2])
OUT = Path("tests/fixtures/huffman/pnx_huffman_pipeline_fixtures.h")

PNX_BLOB_HEADER_BYTES = 8
PNX_SPRITE_FRAME_BYTES = 8


def pad4(n):
    return (n + 3) & ~3


def unpack_4bpp(data, n):
    out = []
    for i in range(n // 2 + (n % 2)):
        b = data[i]
        out.append(b >> 4)
        if len(out) < n:
            out.append(b & 0x0F)
    return out[:n]


table_data = (HUF_DIR / "huffman_table.bin").read_bytes()
assert table_data[0:2] == b"PH"
table_body = table_data[PNX_BLOB_HEADER_BYTES:]
entries, run_bits, _ = bp2.decode_table(table_body)

fixtures = []  # (name, n, encoded_bytes, expected_pixels)

for path in sorted(HUF_DIR.glob("*.bin")):
    if "~bw" in path.name or path.name == "huffman_table.bin":
        continue
    data = path.read_bytes()
    magic = data[0:2]
    if magic == b"PS":
        frame_count = data[3]
        flags = data[4]
        if not (flags & 4):
            continue
        meta_span = frame_count * PNX_SPRITE_FRAME_BYTES
        pal_span = pad4(frame_count)
        frame_meta = data[PNX_BLOB_HEADER_BYTES:PNX_BLOB_HEADER_BYTES + meta_span]
        body_start = PNX_BLOB_HEADER_BYTES + meta_span + pal_span
        seen = {}
        for i in range(frame_count):
            e = frame_meta[i * 8:i * 8 + 8]
            off = e[0] | (e[1] << 8)
            w, h = e[2], e[3]
            if off not in seen:
                seen[off] = (w, h)
        offs_sorted = sorted(seen)
        unit_count = len(offs_sorted)
        offset_table = data[body_start:body_start + 2 * (unit_count + 1)]
        unit_offsets = [int.from_bytes(offset_table[i * 2:i * 2 + 2], "little")
                       for i in range(unit_count + 1)]
        units_start = body_start + 2 * (unit_count + 1)
        for idx, off in enumerate(offs_sorted):
            w, h = seen[off]
            n = w * h
            ub = data[units_start + unit_offsets[idx]:units_start + unit_offsets[idx + 1]]
            expected = bp2.decode_unit_with_table(ub, n, entries, run_bits)
            fixtures.append((f"{path.stem}_f{idx}", n, ub, expected))
    elif magic == b"PA":
        tile_px = data[3]
        tile_count = data[4]
        layout = data[5]
        flags = data[6]
        if layout != 0 or not (flags & 4):
            continue
        tables = pad4(tile_count) * 2
        body = data[PNX_BLOB_HEADER_BYTES:]
        offset_table = body[tables:tables + 2 * (tile_count + 1)]
        unit_offsets = [int.from_bytes(offset_table[i * 2:i * 2 + 2], "little")
                       for i in range(tile_count + 1)]
        units_start = tables + 2 * (tile_count + 1)
        n = tile_px * tile_px
        for i in range(tile_count):
            ub = body[units_start + unit_offsets[i]:units_start + unit_offsets[i + 1]]
            expected = bp2.decode_unit_with_table(ub, n, entries, run_bits)
            fixtures.append((f"{path.stem}_t{i}", n, ub, expected))

print(f"collected {len(fixtures)} real pipeline units, table has {len(entries)} entries")


def c_array(name, values):
    return f"static const uint8_t {name}[] = {{ {', '.join(str(v) for v in values)} }};"


lines = [
    "// GENERATED by tools/gen_huffman_pipeline_fixtures.py -- REAL pipeline output",
    "// (tools/pnx_assets.py, compress = \"huffman\") against Need4Pebble's actual",
    "// content, not synthetic data. Do not edit by hand.",
    "//",
    "// Reuses PnxHuffmanFixture from fixtures/huffman/pnx_huffman_fixtures.h (included",
    "// first, by convention) rather than redeclaring the same struct here -- two",
    "// independent `#pragma once` headers don't deduplicate a type defined in both.",
    "#pragma once",
    "#include <stdint.h>",
    "#include <stddef.h>",
    "",
    c_array("pnx_huffman_pipeline_table", table_body),
    "",
]
for name, n, enc, exp in fixtures:
    ident = name.replace("-", "_").replace(".", "_")
    lines.append(c_array(f"{ident}_henc", enc))
    lines.append(c_array(f"{ident}_hpx", exp))
    lines.append("")

lines.append(f"#define PNX_HUFFMAN_PIPELINE_FIXTURE_COUNT {len(fixtures)}")
lines.append("static const PnxHuffmanFixture pnx_huffman_pipeline_fixtures"
            "[PNX_HUFFMAN_PIPELINE_FIXTURE_COUNT] = {")
for name, n, enc, exp in fixtures:
    ident = name.replace("-", "_").replace(".", "_")
    lines.append(f'\t{{ "{name}", {n}, {ident}_henc, sizeof({ident}_henc), {ident}_hpx }},')
lines.append("};")
lines.append("")

OUT.write_text("\n".join(lines))
print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
