#!/usr/bin/env python3
"""Generates tests/fixtures/huffman/pnx_huffman_fixtures.h from the SAME real pixel
content bpeg_fixtures.h already carries, run through the validated
tools/bpeg2_prototype.py encode_asset_shared_table -- so the C pnx_huffman_decode host
test round-trips against known-good encoder output instead of hand-crafted bytes, the
same "validate the structure in Python first" approach used for the rest of this format.

Not part of the pipeline. Run once to (re)generate the fixture; not run at build time.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import bpeg2_prototype as bp2

SRC = Path("tests/fixtures/bitplane/bpeg_fixtures.h")
OUT_DIR = Path("tests/fixtures/huffman")
OUT = OUT_DIR / "pnx_huffman_fixtures.h"

text = SRC.read_text()
px_arrays = re.findall(r'static const uint8_t (\w+)_px\[\]\s*=\s*\{([^}]*)\};', text)

units = []
for name, body in px_arrays:
    pixels = [int(x) for x in body.split(',') if x.strip()]
    units.append((name, pixels))

pixel_lists = [px for _, px in units]
table_bytes, unit_bytes_list = bp2.encode_asset_shared_table(pixel_lists, max_code_len=16)

# Round-trip check before ever writing the fixture -- a fixture generated from a broken
# encoder would just make the C test agree with the bug.
ns = [len(px) for px in pixel_lists]
decoded = bp2.decode_asset_shared_table(table_bytes, unit_bytes_list, ns)
for (name, px), got in zip(units, decoded):
    assert got == px, f"round-trip failed for {name} before fixture was even written"
print(f"validated {len(units)} units against a freshly built shared table, "
      f"table={len(table_bytes)}B, units={sum(len(u) for u in unit_bytes_list)}B")


def c_array(name, values):
    body = ', '.join(str(v) for v in values)
    return f"static const uint8_t {name}[] = {{ {body} }};"


OUT_DIR.mkdir(parents=True, exist_ok=True)
lines = [
    "// GENERATED by tools/gen_huffman_fixtures.py -- real pixel content from",
    "// tests/fixtures/bitplane/bpeg_fixtures.h, re-encoded against ONE shared Huffman",
    "// table (tools/bpeg2_prototype.py's encode_asset_shared_table) for round-trip",
    "// verification of pnx_huffman_decode. Do not edit by hand.",
    "#pragma once",
    "#include <stdint.h>",
    "#include <stddef.h>",
    "",
    "typedef struct",
    "{",
    "\tconst char* name;",
    "\tuint16_t n;",
    "\tconst uint8_t* encoded;",
    "\tsize_t encoded_len;",
    "\tconst uint8_t* expected;",
    "} PnxHuffmanFixture;",
    "",
    c_array("pnx_huffman_test_table", table_bytes),
    "",
]
for (name, px), enc in zip(units, unit_bytes_list):
    lines.append(c_array(f"{name}_henc", enc))
    lines.append(c_array(f"{name}_hpx", px))
    lines.append("")

lines.append(f"#define PNX_HUFFMAN_FIXTURE_COUNT {len(units)}")
lines.append("static const PnxHuffmanFixture pnx_huffman_fixtures[PNX_HUFFMAN_FIXTURE_COUNT] = {")
for name, px in units:
    lines.append(f'\t{{ "{name}", {len(px)}, {name}_henc, sizeof({name}_henc), {name}_hpx }},')
lines.append("};")
lines.append("")

OUT.write_text("\n".join(lines))
print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
